- hosts: frontends
  gather_facts: true
  tasks:
  - name: Use Uri module for wrting smoke test.
    debug:
      var: ansible_facts
      verbosity: 2
  - name: Fail if 'Ansible has done its job' is not in the page content
    uri:
      url: "http://{{ ansible_hostname }}"
      return_content: yes
    register: data
    failed_when: "'Ansible has done its job' not in data.content"
