---
# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    nics: "{{ item.nics }}"
    key_name: "{{ item.key_name}}"
    security_groups: "{{ item.security_groups }}"
    meta: "{{ item.meta }}"
    state: present
  with_items: "{{ osp_instances }}"

- name: Add floating IP to Servers
  os_floating_ip:
    state: present
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 180
    reuse: yes
  with_items: "{{ osp_instances }}"
  register: osp_servers_floating_ip

- name: Debug print what we got back from the floating ip assignment
  debug:
    msg: "{{ osp_servers_floating_ip.results }}"
    verbosity: 2

- name: Wait for server to be available
  wait_for:
    host: "{{ item.floating_ip.floating_ip_address }}"
    port: 22
    state: started
  with_items: "{{ osp_servers_floating_ip.results }}"
