---
# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    nics: "{{ item.nics }}"
    key_name: "{{ item.key_name}}"
    security_groups: "{{ item.security_groups }}"
    meta: "{{ item.meta }}"
    state: present
  with_items: "{{ osp_instances }}"

- name: Add floating IP to Servers
  os_floating_ip:
    state: present
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 180
    reuse: yes
  with_items: "{{ osp_instances }}"

- name: Wait for server to be available
  wait_for:
    host: "{{ item.name }}"
    port: 22
    delay: 180
    state: open
  with_items: "{{ osp_instances }}"

- name: Add extra keys
  authorized_key:
    user: root
    key: '{{ item }}'
    state: present
  with_file: "{{ osp_keys }}"
